import { chromium } from "playwright-core";
const url = process.argv[2];
const b = await chromium.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe" });
const p = await (await b.newContext({ viewport: { width: 1600, height: 1000 } })).newPage();
const hosts = new Set();
p.on("request", (r) => { const u = new URL(r.url()); if (!u.hostname.includes(new URL(url).hostname)) hosts.add(r.method() + " " + u.origin + u.pathname); });
await p.goto(url, { waitUntil: "networkidle" });
await p.waitForTimeout(2000);
console.log("final:", p.url());
console.log([...hosts].slice(0, 15).join("\n"));
console.log("ls keys:", await p.evaluate(() => Object.keys(localStorage)));
const js = await p.evaluate(() => [...document.scripts].map((s) => s.src).filter(Boolean));
console.log(js.join("\n"));
await b.close();
